### ISSUE TITLE
feedback module

### ISSUE THREAD

**Issue by HanAccount** [shiming-chen/FREE#3]
Hello! I have a new problem:I don't find the feedback module in your paper.But your code of Generator Module exits feedback layer.
@shiming-chen

**Comment by shiming-chen** [comment]
Hi @HanAccount 

FREE has not feedback mechanism.  Your doubt is caused by the name, which follows the code of [TF-VAEGAN](https://github.com/akshitac8/tfvaegan). I have make it more clear.

Best!
